### ISSUE TITLE
Ability to find the latest docs via a URL

### ISSUE THREAD

**Issue by mreynolds** [spring-cloud/spring-cloud-static#2]
With other Spring projects ( http://docs.spring.io/spring-boot/docs/current/ ), a "current" (presumably symlink) directory exists pointing at the latest docs.  With the Spring Cloud projects, there isn't a consistent way to refer to the latest documentation (that I'm aware of).  Would it be possible to generate this?  I'm assuming that the Spring Cloud docs are hosted on GH Pages and thus have the same limitations, which may make this infeasible.

Can we get the same "current" style link for the Spring Cloud docs?

**Comment by OlgaMaciaszek** [comment]
It's been fixed: cloud.spring.io/spring-cloud-static/current/
