### ISSUE TITLE
Missing Horsham.SR in compatibility table

### ISSUE THREAD

**Issue by pgerhard** [spring-cloud/spring-cloud-static#23]
**Describe the bug**
In the announcement for Hoxton.SR4 release the release train Horsham.SR4 is also mentioned. I could not find any details on this release train [here](https://spring.io/projects/spring-cloud). I would have expected that at least the `Table 1. Release train Spring Boot compatibility` contains some information on this release train.

**Sample**
Link to the announcement: https://spring.io/blog/2020/04/27/announcing-spring-cloud-stream-horsham-sr4-3-0-4-release-and-spring-cloud-hoxton-sr4
Link to the page where I expected to find the information: https://spring.io/projects/spring-cloud

**Comment by olegz** [comment]
Horsham is not a spring-cloud release train. It's Spring Cloud Stream - a different framework and different BOM under Spring Cloud Hoxton.

**Comment by pgerhard** [comment]
@olegz ahhh ok, sorry that I got confused. The distinction between Spring Cloud and Spring Cloud Stream was lost on me. Thanks for clearing this up

**Comment by olegz** [comment]
@pgerhard not a problem at all. You are not the first one but hopefully the last ;) since we (in spring-cloud-stream) moving away from named BOMs so Horsham is the last one. After that it will be strictly under spring-cloud, so no more confusion
