### ISSUE TITLE
Broken gradle.build example

### ISSUE THREAD

**Issue by C-Otto** [spring-cloud/spring-cloud-static#25]
**Describe the bug**
https://spring.io/projects/spring-cloud shows a `build.gradle` file below the text "Now that you know which release train to use and the latest service release for that release train you are ready to add the Spring Cloud BOM to your application.". In this file the String used for `mavenBom` is wrong, as with `'` instead of `"` the variable `springCloudVersion` is not resolved.

Broken:
```
mavenBom 'org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}'
```

Fixed:
```
mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
```

**Comment by marcingrzejszczak** [comment]
Fixed, thanks!
