### ISSUE TITLE
Wrong release version of spring cloud config on cloud.spring.io

### ISSUE THREAD

**Issue by ScienJus** [spring-cloud/spring-cloud-static#5]
Hi, i see the lastest release version of spring cloud config on [cloud.spring.io](https://cloud.spring.io/spring-cloud-config/) is `1.3.4`, but in [github project](https://github.com/spring-cloud/spring-cloud-config) is `1.3.2`. so the link takes me to an github 404 page.

**Comment by ryanjbaxter** [comment]
Fixed thanks!
