### ISSUE TITLE
Where is the docuement of Finchley.M4 ?

### ISSUE THREAD

**Issue by diguage** [spring-cloud/spring-cloud-static#6]
I click the link <http://cloud.spring.io/spring-cloud-static/Finchley.M4/>. But it return `File not found`.

Where is the docuement of Finchley.M4 ?

**Comment by ryanjbaxter** [comment]
It doesn't look like it was published.  However Finchley.M5 is the latest milestone and you can find the documentation here http://cloud.spring.io/spring-cloud-static/Finchley.M5/

**Comment by diguage** [comment]
@ryanjbaxter  Thanks a lot. 

Yesterday I also access the <http://cloud.spring.io/spring-cloud-static/Finchley.M5/>. But, it returned `File not found`.

Thank you very much.

**Comment by ryanjbaxter** [comment]
Yeah I created it yesterday morning.
