### ISSUE TITLE
Images not shown in Spring Cloud documents

### ISSUE THREAD

**Issue by ajaygm** [spring-cloud/spring-cloud-static#9]
For example the image rabbit-binder.png on the page (https://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/multi/multi__rabbitmq_binder.html) is pointing to the URL https://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/multi/images/rabbit-binder.png.

In the repository the image does not exist in the folder: https://github.com/spring-cloud/spring-cloud-static/tree/gh-pages/Greenwich.RELEASE/multi/images but it exists in the folder: https://github.com/spring-cloud/spring-cloud-static/tree/gh-pages/Greenwich.RELEASE/images

**Comment by ryanjbaxter** [comment]
@olegz any idea here?  Maybe the path in the streams docs needs to be adjusted?

**Comment by olegz** [comment]
Resolved
